name: lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{tsx,ts,json,html,css,md}
